---
title: "R Notebook"
output: html_notebook
---




```{r}

Sys.setenv(PATH = paste("/anaconda/bin", Sys.getenv("PATH"),sep=":"))

# ## clean and load packages
rm(list = ls())
set.seed(12345)
library (tidyverse)
library (igraph)

system("python -V")
```

```{r data, cache = T}
### Read CLD data# load CLD
dat <- read.csv2('~/Documents/JUAN/PhD-SRC/RS20+Analysis/RS_CLD_2016.csv')
dat <- dat[,-1]
dat$col <- ifelse(dat$Polarity == -1, "#FC8D62","#1F78B4")

g <- filter(dat, Regime.Shift == "Coral transitions") %>% droplevels()
G <- graph_from_data_frame(d = g, directed = TRUE)

# .Call(feedback_arc_set, PACKAGE = 'igraph')
as_edgelist(G)

vertex_names <- unique(c(as.character(g$Tail), as.character(g$Head)))
    
    unique(g$Tail)

    levels(g$Tail)
g
```




```{python}
from igraph import *
import pandas as pd


df = pd.read_csv("~/Documents/JUAN/PhD-SRC/RS20+Analysis/RS_CLD_2016.csv", 
    error_bad_lines=False, sep = ";", header = 0)

edgelist = df.loc[:,["Tail", "Head"]]

tuples = [tuple(x) for x in edgelist.values]

#g = Graph()
#g.add_edges(tuples)

g = Graph.GRG(30,0.2)
g.layout("kk")

#plot(g)

df = pd.read_csv("~/Documents/JUAN/PhD-SRC/RS20+Analysis/RS_CLD_2016.csv", 
    error_bad_lines=False, sep = ";", header = 0)

g = Graph.GRG(30,0.2)
summary(g)

arcs = g.feedback_arc_set()
print(arcs)

```

